//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Callplus.CRM.Tabulador.App.WSRotalogService {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceRotaSoap", Namespace="http://jointecnologia.com/")]
    public partial class WebServiceRota : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback IncluiColetaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaFasesColetaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaStatusAtualColetaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaCaminhoDocumentosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReservaChipsOperationCompleted;
        
        private System.Threading.SendOrPostCallback UploadArquivoOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelaColetaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaDadosProtocoloLIQOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegistraAuditoriaProtocoloLIQOperationCompleted;
        
        private System.Threading.SendOrPostCallback BaseAutenticaOperationCompleted;
        
        private System.Threading.SendOrPostCallback BaseListaSituaoesEntregaOperationCompleted;
        
        private System.Threading.SendOrPostCallback BaseListaEntregasOperationCompleted;
        
        private System.Threading.SendOrPostCallback BaseConcluiEntregaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebServiceRota() {
            this.Url = global::Callplus.CRM.Tabulador.App.Properties.Settings.Default.Callplus_br_com_publiccloud_cpro33117_WebServiceRota;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event IncluiColetaCompletedEventHandler IncluiColetaCompleted;
        
        /// <remarks/>
        public event ConsultaFasesColetaCompletedEventHandler ConsultaFasesColetaCompleted;
        
        /// <remarks/>
        public event ConsultaStatusAtualColetaCompletedEventHandler ConsultaStatusAtualColetaCompleted;
        
        /// <remarks/>
        public event ConsultaCaminhoDocumentosCompletedEventHandler ConsultaCaminhoDocumentosCompleted;
        
        /// <remarks/>
        public event ReservaChipsCompletedEventHandler ReservaChipsCompleted;
        
        /// <remarks/>
        public event UploadArquivoCompletedEventHandler UploadArquivoCompleted;
        
        /// <remarks/>
        public event CancelaColetaCompletedEventHandler CancelaColetaCompleted;
        
        /// <remarks/>
        public event ConsultaDadosProtocoloLIQCompletedEventHandler ConsultaDadosProtocoloLIQCompleted;
        
        /// <remarks/>
        public event RegistraAuditoriaProtocoloLIQCompletedEventHandler RegistraAuditoriaProtocoloLIQCompleted;
        
        /// <remarks/>
        public event BaseAutenticaCompletedEventHandler BaseAutenticaCompleted;
        
        /// <remarks/>
        public event BaseListaSituaoesEntregaCompletedEventHandler BaseListaSituaoesEntregaCompleted;
        
        /// <remarks/>
        public event BaseListaEntregasCompletedEventHandler BaseListaEntregasCompleted;
        
        /// <remarks/>
        public event BaseConcluiEntregaCompletedEventHandler BaseConcluiEntregaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://jointecnologia.com/IncluiColeta", RequestNamespace="http://jointecnologia.com/", ResponseNamespace="http://jointecnologia.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string IncluiColeta(
                    string sLogin, 
                    string sSenha, 
                    string cliCPF, 
                    string cliRG, 
                    string cliNome, 
                    System.DateTime cliDataNascimento, 
                    string cliSexo, 
                    string cliTelefone1, 
                    string cliTelefone2, 
                    string cliTelefone3, 
                    string cliEndereco, 
                    string cliNumero, 
                    string cliComplemento, 
                    string cliBairro, 
                    string cliCidade, 
                    string cliUF, 
                    string cliCEP, 
                    string cliPontoReferencia, 
                    System.DateTime colDataAgendamento, 
                    string colTurnoAgendamento, 
                    int colQuantFolhas, 
                    int colCodTipoDocumento, 
                    string colNumeroAdesao, 
                    string colObservacoes, 
                    string colDddAtivacao, 
                    string colNumeroChip, 
                    string colNumeroOS) {
            object[] results = this.Invoke("IncluiColeta", new object[] {
                        sLogin,
                        sSenha,
                        cliCPF,
                        cliRG,
                        cliNome,
                        cliDataNascimento,
                        cliSexo,
                        cliTelefone1,
                        cliTelefone2,
                        cliTelefone3,
                        cliEndereco,
                        cliNumero,
                        cliComplemento,
                        cliBairro,
                        cliCidade,
                        cliUF,
                        cliCEP,
                        cliPontoReferencia,
                        colDataAgendamento,
                        colTurnoAgendamento,
                        colQuantFolhas,
                        colCodTipoDocumento,
                        colNumeroAdesao,
                        colObservacoes,
                        colDddAtivacao,
                        colNumeroChip,
                        colNumeroOS});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void IncluiColetaAsync(
                    string sLogin, 
                    string sSenha, 
                    string cliCPF, 
                    string cliRG, 
                    string cliNome, 
                    System.DateTime cliDataNascimento, 
                    string cliSexo, 
                    string cliTelefone1, 
                    string cliTelefone2, 
                    string cliTelefone3, 
                    string cliEndereco, 
                    string cliNumero, 
                    string cliComplemento, 
                    string cliBairro, 
                    string cliCidade, 
                    string cliUF, 
                    string cliCEP, 
                    string cliPontoReferencia, 
                    System.DateTime colDataAgendamento, 
                    string colTurnoAgendamento, 
                    int colQuantFolhas, 
                    int colCodTipoDocumento, 
                    string colNumeroAdesao, 
                    string colObservacoes, 
                    string colDddAtivacao, 
                    string colNumeroChip, 
                    string colNumeroOS) {
            this.IncluiColetaAsync(sLogin, sSenha, cliCPF, cliRG, cliNome, cliDataNascimento, cliSexo, cliTelefone1, cliTelefone2, cliTelefone3, cliEndereco, cliNumero, cliComplemento, cliBairro, cliCidade, cliUF, cliCEP, cliPontoReferencia, colDataAgendamento, colTurnoAgendamento, colQuantFolhas, colCodTipoDocumento, colNumeroAdesao, colObservacoes, colDddAtivacao, colNumeroChip, colNumeroOS, null);
        }
        
        /// <remarks/>
        public void IncluiColetaAsync(
                    string sLogin, 
                    string sSenha, 
                    string cliCPF, 
                    string cliRG, 
                    string cliNome, 
                    System.DateTime cliDataNascimento, 
                    string cliSexo, 
                    string cliTelefone1, 
                    string cliTelefone2, 
                    string cliTelefone3, 
                    string cliEndereco, 
                    string cliNumero, 
                    string cliComplemento, 
                    string cliBairro, 
                    string cliCidade, 
                    string cliUF, 
                    string cliCEP, 
                    string cliPontoReferencia, 
                    System.DateTime colDataAgendamento, 
                    string colTurnoAgendamento, 
                    int colQuantFolhas, 
                    int colCodTipoDocumento, 
                    string colNumeroAdesao, 
                    string colObservacoes, 
                    string colDddAtivacao, 
                    string colNumeroChip, 
                    string colNumeroOS, 
                    object userState) {
            if ((this.IncluiColetaOperationCompleted == null)) {
                this.IncluiColetaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIncluiColetaOperationCompleted);
            }
            this.InvokeAsync("IncluiColeta", new object[] {
                        sLogin,
                        sSenha,
                        cliCPF,
                        cliRG,
                        cliNome,
                        cliDataNascimento,
                        cliSexo,
                        cliTelefone1,
                        cliTelefone2,
                        cliTelefone3,
                        cliEndereco,
                        cliNumero,
                        cliComplemento,
                        cliBairro,
                        cliCidade,
                        cliUF,
                        cliCEP,
                        cliPontoReferencia,
                        colDataAgendamento,
                        colTurnoAgendamento,
                        colQuantFolhas,
                        colCodTipoDocumento,
                        colNumeroAdesao,
                        colObservacoes,
                        colDddAtivacao,
                        colNumeroChip,
                        colNumeroOS}, this.IncluiColetaOperationCompleted, userState);
        }
        
        private void OnIncluiColetaOperationCompleted(object arg) {
            if ((this.IncluiColetaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IncluiColetaCompleted(this, new IncluiColetaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://jointecnologia.com/ConsultaFasesColeta", RequestNamespace="http://jointecnologia.com/", ResponseNamespace="http://jointecnologia.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ConsultaFasesColeta(string sLogin, string sSenha, int CodigoColeta) {
            object[] results = this.Invoke("ConsultaFasesColeta", new object[] {
                        sLogin,
                        sSenha,
                        CodigoColeta});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaFasesColetaAsync(string sLogin, string sSenha, int CodigoColeta) {
            this.ConsultaFasesColetaAsync(sLogin, sSenha, CodigoColeta, null);
        }
        
        /// <remarks/>
        public void ConsultaFasesColetaAsync(string sLogin, string sSenha, int CodigoColeta, object userState) {
            if ((this.ConsultaFasesColetaOperationCompleted == null)) {
                this.ConsultaFasesColetaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaFasesColetaOperationCompleted);
            }
            this.InvokeAsync("ConsultaFasesColeta", new object[] {
                        sLogin,
                        sSenha,
                        CodigoColeta}, this.ConsultaFasesColetaOperationCompleted, userState);
        }
        
        private void OnConsultaFasesColetaOperationCompleted(object arg) {
            if ((this.ConsultaFasesColetaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaFasesColetaCompleted(this, new ConsultaFasesColetaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://jointecnologia.com/ConsultaStatusAtualColeta", RequestNamespace="http://jointecnologia.com/", ResponseNamespace="http://jointecnologia.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConsultaStatusAtualColeta(string sLogin, string sSenha, int CodigoColeta) {
            object[] results = this.Invoke("ConsultaStatusAtualColeta", new object[] {
                        sLogin,
                        sSenha,
                        CodigoColeta});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaStatusAtualColetaAsync(string sLogin, string sSenha, int CodigoColeta) {
            this.ConsultaStatusAtualColetaAsync(sLogin, sSenha, CodigoColeta, null);
        }
        
        /// <remarks/>
        public void ConsultaStatusAtualColetaAsync(string sLogin, string sSenha, int CodigoColeta, object userState) {
            if ((this.ConsultaStatusAtualColetaOperationCompleted == null)) {
                this.ConsultaStatusAtualColetaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaStatusAtualColetaOperationCompleted);
            }
            this.InvokeAsync("ConsultaStatusAtualColeta", new object[] {
                        sLogin,
                        sSenha,
                        CodigoColeta}, this.ConsultaStatusAtualColetaOperationCompleted, userState);
        }
        
        private void OnConsultaStatusAtualColetaOperationCompleted(object arg) {
            if ((this.ConsultaStatusAtualColetaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaStatusAtualColetaCompleted(this, new ConsultaStatusAtualColetaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://jointecnologia.com/ConsultaCaminhoDocumentos", RequestNamespace="http://jointecnologia.com/", ResponseNamespace="http://jointecnologia.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ConsultaCaminhoDocumentos(string sLogin, string sSenha, int CodigoColeta) {
            object[] results = this.Invoke("ConsultaCaminhoDocumentos", new object[] {
                        sLogin,
                        sSenha,
                        CodigoColeta});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaCaminhoDocumentosAsync(string sLogin, string sSenha, int CodigoColeta) {
            this.ConsultaCaminhoDocumentosAsync(sLogin, sSenha, CodigoColeta, null);
        }
        
        /// <remarks/>
        public void ConsultaCaminhoDocumentosAsync(string sLogin, string sSenha, int CodigoColeta, object userState) {
            if ((this.ConsultaCaminhoDocumentosOperationCompleted == null)) {
                this.ConsultaCaminhoDocumentosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaCaminhoDocumentosOperationCompleted);
            }
            this.InvokeAsync("ConsultaCaminhoDocumentos", new object[] {
                        sLogin,
                        sSenha,
                        CodigoColeta}, this.ConsultaCaminhoDocumentosOperationCompleted, userState);
        }
        
        private void OnConsultaCaminhoDocumentosOperationCompleted(object arg) {
            if ((this.ConsultaCaminhoDocumentosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaCaminhoDocumentosCompleted(this, new ConsultaCaminhoDocumentosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://jointecnologia.com/ReservaChips", RequestNamespace="http://jointecnologia.com/", ResponseNamespace="http://jointecnologia.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ReservaChips(string sLogin, string sSenha, string DDDAtivacao, string CEPEntrega, int QuantidadeChips) {
            object[] results = this.Invoke("ReservaChips", new object[] {
                        sLogin,
                        sSenha,
                        DDDAtivacao,
                        CEPEntrega,
                        QuantidadeChips});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ReservaChipsAsync(string sLogin, string sSenha, string DDDAtivacao, string CEPEntrega, int QuantidadeChips) {
            this.ReservaChipsAsync(sLogin, sSenha, DDDAtivacao, CEPEntrega, QuantidadeChips, null);
        }
        
        /// <remarks/>
        public void ReservaChipsAsync(string sLogin, string sSenha, string DDDAtivacao, string CEPEntrega, int QuantidadeChips, object userState) {
            if ((this.ReservaChipsOperationCompleted == null)) {
                this.ReservaChipsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReservaChipsOperationCompleted);
            }
            this.InvokeAsync("ReservaChips", new object[] {
                        sLogin,
                        sSenha,
                        DDDAtivacao,
                        CEPEntrega,
                        QuantidadeChips}, this.ReservaChipsOperationCompleted, userState);
        }
        
        private void OnReservaChipsOperationCompleted(object arg) {
            if ((this.ReservaChipsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReservaChipsCompleted(this, new ReservaChipsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://jointecnologia.com/UploadArquivo", RequestNamespace="http://jointecnologia.com/", ResponseNamespace="http://jointecnologia.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UploadArquivo(string sLogin, string sSenha, int CodigoColeta, string sDescricaoArquivo, string sNomeOriginalArquivo, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] Arquivo) {
            object[] results = this.Invoke("UploadArquivo", new object[] {
                        sLogin,
                        sSenha,
                        CodigoColeta,
                        sDescricaoArquivo,
                        sNomeOriginalArquivo,
                        Arquivo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UploadArquivoAsync(string sLogin, string sSenha, int CodigoColeta, string sDescricaoArquivo, string sNomeOriginalArquivo, byte[] Arquivo) {
            this.UploadArquivoAsync(sLogin, sSenha, CodigoColeta, sDescricaoArquivo, sNomeOriginalArquivo, Arquivo, null);
        }
        
        /// <remarks/>
        public void UploadArquivoAsync(string sLogin, string sSenha, int CodigoColeta, string sDescricaoArquivo, string sNomeOriginalArquivo, byte[] Arquivo, object userState) {
            if ((this.UploadArquivoOperationCompleted == null)) {
                this.UploadArquivoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadArquivoOperationCompleted);
            }
            this.InvokeAsync("UploadArquivo", new object[] {
                        sLogin,
                        sSenha,
                        CodigoColeta,
                        sDescricaoArquivo,
                        sNomeOriginalArquivo,
                        Arquivo}, this.UploadArquivoOperationCompleted, userState);
        }
        
        private void OnUploadArquivoOperationCompleted(object arg) {
            if ((this.UploadArquivoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadArquivoCompleted(this, new UploadArquivoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://jointecnologia.com/CancelaColeta", RequestNamespace="http://jointecnologia.com/", ResponseNamespace="http://jointecnologia.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CancelaColeta(string sLogin, string sSenha, int CodigoColeta) {
            object[] results = this.Invoke("CancelaColeta", new object[] {
                        sLogin,
                        sSenha,
                        CodigoColeta});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CancelaColetaAsync(string sLogin, string sSenha, int CodigoColeta) {
            this.CancelaColetaAsync(sLogin, sSenha, CodigoColeta, null);
        }
        
        /// <remarks/>
        public void CancelaColetaAsync(string sLogin, string sSenha, int CodigoColeta, object userState) {
            if ((this.CancelaColetaOperationCompleted == null)) {
                this.CancelaColetaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelaColetaOperationCompleted);
            }
            this.InvokeAsync("CancelaColeta", new object[] {
                        sLogin,
                        sSenha,
                        CodigoColeta}, this.CancelaColetaOperationCompleted, userState);
        }
        
        private void OnCancelaColetaOperationCompleted(object arg) {
            if ((this.CancelaColetaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelaColetaCompleted(this, new CancelaColetaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://jointecnologia.com/ConsultaDadosProtocoloLIQ", RequestNamespace="http://jointecnologia.com/", ResponseNamespace="http://jointecnologia.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ConsultaDadosProtocoloLIQ(string sLogin, string sSenha, string NumeroAdesao) {
            object[] results = this.Invoke("ConsultaDadosProtocoloLIQ", new object[] {
                        sLogin,
                        sSenha,
                        NumeroAdesao});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaDadosProtocoloLIQAsync(string sLogin, string sSenha, string NumeroAdesao) {
            this.ConsultaDadosProtocoloLIQAsync(sLogin, sSenha, NumeroAdesao, null);
        }
        
        /// <remarks/>
        public void ConsultaDadosProtocoloLIQAsync(string sLogin, string sSenha, string NumeroAdesao, object userState) {
            if ((this.ConsultaDadosProtocoloLIQOperationCompleted == null)) {
                this.ConsultaDadosProtocoloLIQOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaDadosProtocoloLIQOperationCompleted);
            }
            this.InvokeAsync("ConsultaDadosProtocoloLIQ", new object[] {
                        sLogin,
                        sSenha,
                        NumeroAdesao}, this.ConsultaDadosProtocoloLIQOperationCompleted, userState);
        }
        
        private void OnConsultaDadosProtocoloLIQOperationCompleted(object arg) {
            if ((this.ConsultaDadosProtocoloLIQCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaDadosProtocoloLIQCompleted(this, new ConsultaDadosProtocoloLIQCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://jointecnologia.com/RegistraAuditoriaProtocoloLIQ", RequestNamespace="http://jointecnologia.com/", ResponseNamespace="http://jointecnologia.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RegistraAuditoriaProtocoloLIQ(string sLogin, string sSenha, string NumeroAdesao, int CodigoTratamento, int CodigoObjecao) {
            object[] results = this.Invoke("RegistraAuditoriaProtocoloLIQ", new object[] {
                        sLogin,
                        sSenha,
                        NumeroAdesao,
                        CodigoTratamento,
                        CodigoObjecao});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RegistraAuditoriaProtocoloLIQAsync(string sLogin, string sSenha, string NumeroAdesao, int CodigoTratamento, int CodigoObjecao) {
            this.RegistraAuditoriaProtocoloLIQAsync(sLogin, sSenha, NumeroAdesao, CodigoTratamento, CodigoObjecao, null);
        }
        
        /// <remarks/>
        public void RegistraAuditoriaProtocoloLIQAsync(string sLogin, string sSenha, string NumeroAdesao, int CodigoTratamento, int CodigoObjecao, object userState) {
            if ((this.RegistraAuditoriaProtocoloLIQOperationCompleted == null)) {
                this.RegistraAuditoriaProtocoloLIQOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegistraAuditoriaProtocoloLIQOperationCompleted);
            }
            this.InvokeAsync("RegistraAuditoriaProtocoloLIQ", new object[] {
                        sLogin,
                        sSenha,
                        NumeroAdesao,
                        CodigoTratamento,
                        CodigoObjecao}, this.RegistraAuditoriaProtocoloLIQOperationCompleted, userState);
        }
        
        private void OnRegistraAuditoriaProtocoloLIQOperationCompleted(object arg) {
            if ((this.RegistraAuditoriaProtocoloLIQCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegistraAuditoriaProtocoloLIQCompleted(this, new RegistraAuditoriaProtocoloLIQCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://jointecnologia.com/BaseAutentica", RequestNamespace="http://jointecnologia.com/", ResponseNamespace="http://jointecnologia.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet BaseAutentica(string sLogin, string sSenha) {
            object[] results = this.Invoke("BaseAutentica", new object[] {
                        sLogin,
                        sSenha});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void BaseAutenticaAsync(string sLogin, string sSenha) {
            this.BaseAutenticaAsync(sLogin, sSenha, null);
        }
        
        /// <remarks/>
        public void BaseAutenticaAsync(string sLogin, string sSenha, object userState) {
            if ((this.BaseAutenticaOperationCompleted == null)) {
                this.BaseAutenticaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBaseAutenticaOperationCompleted);
            }
            this.InvokeAsync("BaseAutentica", new object[] {
                        sLogin,
                        sSenha}, this.BaseAutenticaOperationCompleted, userState);
        }
        
        private void OnBaseAutenticaOperationCompleted(object arg) {
            if ((this.BaseAutenticaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BaseAutenticaCompleted(this, new BaseAutenticaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://jointecnologia.com/BaseListaSituaoesEntrega", RequestNamespace="http://jointecnologia.com/", ResponseNamespace="http://jointecnologia.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet BaseListaSituaoesEntrega(string sLogin, string sSenha, int CodigoBase) {
            object[] results = this.Invoke("BaseListaSituaoesEntrega", new object[] {
                        sLogin,
                        sSenha,
                        CodigoBase});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void BaseListaSituaoesEntregaAsync(string sLogin, string sSenha, int CodigoBase) {
            this.BaseListaSituaoesEntregaAsync(sLogin, sSenha, CodigoBase, null);
        }
        
        /// <remarks/>
        public void BaseListaSituaoesEntregaAsync(string sLogin, string sSenha, int CodigoBase, object userState) {
            if ((this.BaseListaSituaoesEntregaOperationCompleted == null)) {
                this.BaseListaSituaoesEntregaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBaseListaSituaoesEntregaOperationCompleted);
            }
            this.InvokeAsync("BaseListaSituaoesEntrega", new object[] {
                        sLogin,
                        sSenha,
                        CodigoBase}, this.BaseListaSituaoesEntregaOperationCompleted, userState);
        }
        
        private void OnBaseListaSituaoesEntregaOperationCompleted(object arg) {
            if ((this.BaseListaSituaoesEntregaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BaseListaSituaoesEntregaCompleted(this, new BaseListaSituaoesEntregaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://jointecnologia.com/BaseListaEntregas", RequestNamespace="http://jointecnologia.com/", ResponseNamespace="http://jointecnologia.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet BaseListaEntregas(string sLogin, string sSenha, int CodigoBase) {
            object[] results = this.Invoke("BaseListaEntregas", new object[] {
                        sLogin,
                        sSenha,
                        CodigoBase});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void BaseListaEntregasAsync(string sLogin, string sSenha, int CodigoBase) {
            this.BaseListaEntregasAsync(sLogin, sSenha, CodigoBase, null);
        }
        
        /// <remarks/>
        public void BaseListaEntregasAsync(string sLogin, string sSenha, int CodigoBase, object userState) {
            if ((this.BaseListaEntregasOperationCompleted == null)) {
                this.BaseListaEntregasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBaseListaEntregasOperationCompleted);
            }
            this.InvokeAsync("BaseListaEntregas", new object[] {
                        sLogin,
                        sSenha,
                        CodigoBase}, this.BaseListaEntregasOperationCompleted, userState);
        }
        
        private void OnBaseListaEntregasOperationCompleted(object arg) {
            if ((this.BaseListaEntregasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BaseListaEntregasCompleted(this, new BaseListaEntregasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://jointecnologia.com/BaseConcluiEntrega", RequestNamespace="http://jointecnologia.com/", ResponseNamespace="http://jointecnologia.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string BaseConcluiEntrega(string sLogin, string sSenha, int CodigoBase, int ColCodigo, int CodigoSituacao, string SubStatusEntregue, string ObservacoesAdicionais, string sNomeOriginalArquivo, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] Arquivo) {
            object[] results = this.Invoke("BaseConcluiEntrega", new object[] {
                        sLogin,
                        sSenha,
                        CodigoBase,
                        ColCodigo,
                        CodigoSituacao,
                        SubStatusEntregue,
                        ObservacoesAdicionais,
                        sNomeOriginalArquivo,
                        Arquivo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void BaseConcluiEntregaAsync(string sLogin, string sSenha, int CodigoBase, int ColCodigo, int CodigoSituacao, string SubStatusEntregue, string ObservacoesAdicionais, string sNomeOriginalArquivo, byte[] Arquivo) {
            this.BaseConcluiEntregaAsync(sLogin, sSenha, CodigoBase, ColCodigo, CodigoSituacao, SubStatusEntregue, ObservacoesAdicionais, sNomeOriginalArquivo, Arquivo, null);
        }
        
        /// <remarks/>
        public void BaseConcluiEntregaAsync(string sLogin, string sSenha, int CodigoBase, int ColCodigo, int CodigoSituacao, string SubStatusEntregue, string ObservacoesAdicionais, string sNomeOriginalArquivo, byte[] Arquivo, object userState) {
            if ((this.BaseConcluiEntregaOperationCompleted == null)) {
                this.BaseConcluiEntregaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBaseConcluiEntregaOperationCompleted);
            }
            this.InvokeAsync("BaseConcluiEntrega", new object[] {
                        sLogin,
                        sSenha,
                        CodigoBase,
                        ColCodigo,
                        CodigoSituacao,
                        SubStatusEntregue,
                        ObservacoesAdicionais,
                        sNomeOriginalArquivo,
                        Arquivo}, this.BaseConcluiEntregaOperationCompleted, userState);
        }
        
        private void OnBaseConcluiEntregaOperationCompleted(object arg) {
            if ((this.BaseConcluiEntregaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BaseConcluiEntregaCompleted(this, new BaseConcluiEntregaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void IncluiColetaCompletedEventHandler(object sender, IncluiColetaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IncluiColetaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IncluiColetaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ConsultaFasesColetaCompletedEventHandler(object sender, ConsultaFasesColetaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaFasesColetaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaFasesColetaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ConsultaStatusAtualColetaCompletedEventHandler(object sender, ConsultaStatusAtualColetaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaStatusAtualColetaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaStatusAtualColetaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ConsultaCaminhoDocumentosCompletedEventHandler(object sender, ConsultaCaminhoDocumentosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaCaminhoDocumentosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaCaminhoDocumentosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ReservaChipsCompletedEventHandler(object sender, ReservaChipsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReservaChipsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReservaChipsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void UploadArquivoCompletedEventHandler(object sender, UploadArquivoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadArquivoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadArquivoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void CancelaColetaCompletedEventHandler(object sender, CancelaColetaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CancelaColetaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CancelaColetaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ConsultaDadosProtocoloLIQCompletedEventHandler(object sender, ConsultaDadosProtocoloLIQCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaDadosProtocoloLIQCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaDadosProtocoloLIQCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void RegistraAuditoriaProtocoloLIQCompletedEventHandler(object sender, RegistraAuditoriaProtocoloLIQCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegistraAuditoriaProtocoloLIQCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegistraAuditoriaProtocoloLIQCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void BaseAutenticaCompletedEventHandler(object sender, BaseAutenticaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BaseAutenticaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BaseAutenticaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void BaseListaSituaoesEntregaCompletedEventHandler(object sender, BaseListaSituaoesEntregaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BaseListaSituaoesEntregaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BaseListaSituaoesEntregaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void BaseListaEntregasCompletedEventHandler(object sender, BaseListaEntregasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BaseListaEntregasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BaseListaEntregasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void BaseConcluiEntregaCompletedEventHandler(object sender, BaseConcluiEntregaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BaseConcluiEntregaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BaseConcluiEntregaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591