//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Callplus.CRM.Tabulador.App.WSAgentEvent {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSAgentEvent.WSAgentEventSoap")]
    public interface WSAgentEventSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNextEvent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Callplus.CRM.Tabulador.App.WSAgentEvent.ObjEvent GetNextEvent(int AgentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNextEvent", ReplyAction="*")]
        System.Threading.Tasks.Task<Callplus.CRM.Tabulador.App.WSAgentEvent.ObjEvent> GetNextEventAsync(int AgentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllNextEvents", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Callplus.CRM.Tabulador.App.WSAgentEvent.ObjEvent[] GetAllNextEvents();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllNextEvents", ReplyAction="*")]
        System.Threading.Tasks.Task<Callplus.CRM.Tabulador.App.WSAgentEvent.ObjEvent[]> GetAllNextEventsAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ObjEvent : object, System.ComponentModel.INotifyPropertyChanged {
        
        private EnumAgentEventType agentEventTypeField;
        
        private object eventObjectField;
        
        private ObjLoginCCM eventObjectLoginCCMField;
        
        private ObjSendMsgToSupervisorFail eventSendMsgToSupervisorFailField;
        
        private ObjNewMsgFromSupervisor eventNewMsgFromSupervisorField;
        
        private ObjLoginCampaign eventObjectLoginCampaignField;
        
        private ObjLogout eventObjectLogoutField;
        
        private ObjAgentChangeStatus eventObjectAgentChangeStatusField;
        
        private ObjScreenPop eventObjectScreenPopField;
        
        private ObjThirdPartyScreenPop eventObjectThirdPartyScreenPopField;
        
        private ObjNewChat eventObjectNewChatField;
        
        private ObjNewChatMsg eventObjectNewChatMsgField;
        
        private ObjNewMessage eventObjectNewMessageField;
        
        private ObjManualCallState eventObjectManualCallStateField;
        
        private ObjPreviewCallState eventObjectPreviewCallStateField;
        
        private ObjPreviewCallResult eventObjectPreviewCallResultField;
        
        private ObjCustomerClosureConfirmation eventObjectCustomerClosureConfirmationField;
        
        private ObjPreviewDnisLocateResult eventObjPreviewDnisLocateResultField;
        
        private ObjActiveCall[] eventObjectActiveCallField;
        
        private int genericIntField;
        
        private string genericStringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public EnumAgentEventType AgentEventType {
            get {
                return this.agentEventTypeField;
            }
            set {
                this.agentEventTypeField = value;
                this.RaisePropertyChanged("AgentEventType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public object EventObject {
            get {
                return this.eventObjectField;
            }
            set {
                this.eventObjectField = value;
                this.RaisePropertyChanged("EventObject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ObjLoginCCM EventObjectLoginCCM {
            get {
                return this.eventObjectLoginCCMField;
            }
            set {
                this.eventObjectLoginCCMField = value;
                this.RaisePropertyChanged("EventObjectLoginCCM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public ObjSendMsgToSupervisorFail EventSendMsgToSupervisorFail {
            get {
                return this.eventSendMsgToSupervisorFailField;
            }
            set {
                this.eventSendMsgToSupervisorFailField = value;
                this.RaisePropertyChanged("EventSendMsgToSupervisorFail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public ObjNewMsgFromSupervisor EventNewMsgFromSupervisor {
            get {
                return this.eventNewMsgFromSupervisorField;
            }
            set {
                this.eventNewMsgFromSupervisorField = value;
                this.RaisePropertyChanged("EventNewMsgFromSupervisor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public ObjLoginCampaign EventObjectLoginCampaign {
            get {
                return this.eventObjectLoginCampaignField;
            }
            set {
                this.eventObjectLoginCampaignField = value;
                this.RaisePropertyChanged("EventObjectLoginCampaign");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public ObjLogout EventObjectLogout {
            get {
                return this.eventObjectLogoutField;
            }
            set {
                this.eventObjectLogoutField = value;
                this.RaisePropertyChanged("EventObjectLogout");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public ObjAgentChangeStatus EventObjectAgentChangeStatus {
            get {
                return this.eventObjectAgentChangeStatusField;
            }
            set {
                this.eventObjectAgentChangeStatusField = value;
                this.RaisePropertyChanged("EventObjectAgentChangeStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public ObjScreenPop EventObjectScreenPop {
            get {
                return this.eventObjectScreenPopField;
            }
            set {
                this.eventObjectScreenPopField = value;
                this.RaisePropertyChanged("EventObjectScreenPop");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public ObjThirdPartyScreenPop EventObjectThirdPartyScreenPop {
            get {
                return this.eventObjectThirdPartyScreenPopField;
            }
            set {
                this.eventObjectThirdPartyScreenPopField = value;
                this.RaisePropertyChanged("EventObjectThirdPartyScreenPop");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public ObjNewChat EventObjectNewChat {
            get {
                return this.eventObjectNewChatField;
            }
            set {
                this.eventObjectNewChatField = value;
                this.RaisePropertyChanged("EventObjectNewChat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public ObjNewChatMsg EventObjectNewChatMsg {
            get {
                return this.eventObjectNewChatMsgField;
            }
            set {
                this.eventObjectNewChatMsgField = value;
                this.RaisePropertyChanged("EventObjectNewChatMsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public ObjNewMessage EventObjectNewMessage {
            get {
                return this.eventObjectNewMessageField;
            }
            set {
                this.eventObjectNewMessageField = value;
                this.RaisePropertyChanged("EventObjectNewMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public ObjManualCallState EventObjectManualCallState {
            get {
                return this.eventObjectManualCallStateField;
            }
            set {
                this.eventObjectManualCallStateField = value;
                this.RaisePropertyChanged("EventObjectManualCallState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public ObjPreviewCallState EventObjectPreviewCallState {
            get {
                return this.eventObjectPreviewCallStateField;
            }
            set {
                this.eventObjectPreviewCallStateField = value;
                this.RaisePropertyChanged("EventObjectPreviewCallState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public ObjPreviewCallResult EventObjectPreviewCallResult {
            get {
                return this.eventObjectPreviewCallResultField;
            }
            set {
                this.eventObjectPreviewCallResultField = value;
                this.RaisePropertyChanged("EventObjectPreviewCallResult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public ObjCustomerClosureConfirmation EventObjectCustomerClosureConfirmation {
            get {
                return this.eventObjectCustomerClosureConfirmationField;
            }
            set {
                this.eventObjectCustomerClosureConfirmationField = value;
                this.RaisePropertyChanged("EventObjectCustomerClosureConfirmation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public ObjPreviewDnisLocateResult EventObjPreviewDnisLocateResult {
            get {
                return this.eventObjPreviewDnisLocateResultField;
            }
            set {
                this.eventObjPreviewDnisLocateResultField = value;
                this.RaisePropertyChanged("EventObjPreviewDnisLocateResult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=18)]
        public ObjActiveCall[] EventObjectActiveCall {
            get {
                return this.eventObjectActiveCallField;
            }
            set {
                this.eventObjectActiveCallField = value;
                this.RaisePropertyChanged("EventObjectActiveCall");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public int GenericInt {
            get {
                return this.genericIntField;
            }
            set {
                this.genericIntField = value;
                this.RaisePropertyChanged("GenericInt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string GenericString {
            get {
                return this.genericStringField;
            }
            set {
                this.genericStringField = value;
                this.RaisePropertyChanged("GenericString");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum EnumAgentEventType {
        
        /// <remarks/>
        Nothing,
        
        /// <remarks/>
        LoginCCM,
        
        /// <remarks/>
        LogoutCCM,
        
        /// <remarks/>
        LoginCampaign,
        
        /// <remarks/>
        LogoutCampaign,
        
        /// <remarks/>
        ChangeStatus,
        
        /// <remarks/>
        ScreenPop,
        
        /// <remarks/>
        ChangeStatusFail,
        
        /// <remarks/>
        DispositionRequestFail,
        
        /// <remarks/>
        LoginCCMFail,
        
        /// <remarks/>
        LoginCampaignFail,
        
        /// <remarks/>
        LogoutCCMFail,
        
        /// <remarks/>
        LogoutCampaignFail,
        
        /// <remarks/>
        OnlineCampaignChangeStatusId,
        
        /// <remarks/>
        PassCode,
        
        /// <remarks/>
        NewChat,
        
        /// <remarks/>
        NewChatMsg,
        
        /// <remarks/>
        EndChat,
        
        /// <remarks/>
        NewMessage,
        
        /// <remarks/>
        ConsultingRequestFail,
        
        /// <remarks/>
        ActiveCall,
        
        /// <remarks/>
        ManualCallRequestFail,
        
        /// <remarks/>
        ChangeManualCallState,
        
        /// <remarks/>
        RedialRequestFail,
        
        /// <remarks/>
        RedialSuccess,
        
        /// <remarks/>
        ListActiveCalls,
        
        /// <remarks/>
        PrivateCallbackFail,
        
        /// <remarks/>
        ThirdPartyScreenPop,
        
        /// <remarks/>
        ChangePreviewCallState,
        
        /// <remarks/>
        ChangePreviewCallResult,
        
        /// <remarks/>
        CustomerClosureConfirmation,
        
        /// <remarks/>
        PreviewDnisLocateResult,
        
        /// <remarks/>
        BlindTransferRequestFail,
        
        /// <remarks/>
        SendMsgToSupervisorFail,
        
        /// <remarks/>
        NewMsgFromSupervisor,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ObjActiveCall : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int callIdField;
        
        private bool customerCallField;
        
        private string phoneNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int CallId {
            get {
                return this.callIdField;
            }
            set {
                this.callIdField = value;
                this.RaisePropertyChanged("CallId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool CustomerCall {
            get {
                return this.customerCallField;
            }
            set {
                this.customerCallField = value;
                this.RaisePropertyChanged("CustomerCall");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
                this.RaisePropertyChanged("PhoneNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ObjPreviewDnisLocateResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string phoneNumberField;
        
        private string dispositionField;
        
        private string resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
                this.RaisePropertyChanged("PhoneNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Disposition {
            get {
                return this.dispositionField;
            }
            set {
                this.dispositionField = value;
                this.RaisePropertyChanged("Disposition");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ObjCustomerClosureConfirmation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string campaignDataField;
        
        private string customerIdField;
        
        private string tableNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CampaignData {
            get {
                return this.campaignDataField;
            }
            set {
                this.campaignDataField = value;
                this.RaisePropertyChanged("CampaignData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CustomerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
                this.RaisePropertyChanged("CustomerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TableName {
            get {
                return this.tableNameField;
            }
            set {
                this.tableNameField = value;
                this.RaisePropertyChanged("TableName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ObjPreviewCallResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int callIdField;
        
        private string resultField;
        
        private string phoneNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int CallId {
            get {
                return this.callIdField;
            }
            set {
                this.callIdField = value;
                this.RaisePropertyChanged("CallId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
                this.RaisePropertyChanged("PhoneNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ObjPreviewCallState : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int callIdField;
        
        private EnumCallControlStatusId callStateField;
        
        private string phoneNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int CallId {
            get {
                return this.callIdField;
            }
            set {
                this.callIdField = value;
                this.RaisePropertyChanged("CallId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public EnumCallControlStatusId CallState {
            get {
                return this.callStateField;
            }
            set {
                this.callStateField = value;
                this.RaisePropertyChanged("CallState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
                this.RaisePropertyChanged("PhoneNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum EnumCallControlStatusId {
        
        /// <remarks/>
        Nothing,
        
        /// <remarks/>
        Started,
        
        /// <remarks/>
        Alerting,
        
        /// <remarks/>
        CustomerConnected,
        
        /// <remarks/>
        Routing,
        
        /// <remarks/>
        AgentConnected,
        
        /// <remarks/>
        Finished,
        
        /// <remarks/>
        Consulting,
        
        /// <remarks/>
        Transfering,
        
        /// <remarks/>
        Queue,
        
        /// <remarks/>
        Holding,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ObjManualCallState : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int callIdField;
        
        private EnumCallControlStatusId callStateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int CallId {
            get {
                return this.callIdField;
            }
            set {
                this.callIdField = value;
                this.RaisePropertyChanged("CallId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public EnumCallControlStatusId CallState {
            get {
                return this.callStateField;
            }
            set {
                this.callStateField = value;
                this.RaisePropertyChanged("CallState");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ObjNewMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int campaignIdField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int CampaignId {
            get {
                return this.campaignIdField;
            }
            set {
                this.campaignIdField = value;
                this.RaisePropertyChanged("CampaignId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ObjNewChatMsg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int chatIdField;
        
        private int agentIdField;
        
        private string msgField;
        
        private string msgDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ChatId {
            get {
                return this.chatIdField;
            }
            set {
                this.chatIdField = value;
                this.RaisePropertyChanged("ChatId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int AgentId {
            get {
                return this.agentIdField;
            }
            set {
                this.agentIdField = value;
                this.RaisePropertyChanged("AgentId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
                this.RaisePropertyChanged("Msg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MsgDate {
            get {
                return this.msgDateField;
            }
            set {
                this.msgDateField = value;
                this.RaisePropertyChanged("MsgDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ObjNewChat : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int chatIdField;
        
        private int campaignIdField;
        
        private string customerIdField;
        
        private string customerNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ChatId {
            get {
                return this.chatIdField;
            }
            set {
                this.chatIdField = value;
                this.RaisePropertyChanged("ChatId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int CampaignId {
            get {
                return this.campaignIdField;
            }
            set {
                this.campaignIdField = value;
                this.RaisePropertyChanged("CampaignId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CustomerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
                this.RaisePropertyChanged("CustomerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CustomerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
                this.RaisePropertyChanged("CustomerName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ObjThirdPartyScreenPop : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int thirdPartyCallIdField;
        
        private int campaignIdField;
        
        private string campaignCodeField;
        
        private string phoneNumberField;
        
        private string skillGroupField;
        
        private bool priorityCampaignField;
        
        private string campaignDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ThirdPartyCallId {
            get {
                return this.thirdPartyCallIdField;
            }
            set {
                this.thirdPartyCallIdField = value;
                this.RaisePropertyChanged("ThirdPartyCallId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int CampaignId {
            get {
                return this.campaignIdField;
            }
            set {
                this.campaignIdField = value;
                this.RaisePropertyChanged("CampaignId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CampaignCode {
            get {
                return this.campaignCodeField;
            }
            set {
                this.campaignCodeField = value;
                this.RaisePropertyChanged("CampaignCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
                this.RaisePropertyChanged("PhoneNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SkillGroup {
            get {
                return this.skillGroupField;
            }
            set {
                this.skillGroupField = value;
                this.RaisePropertyChanged("SkillGroup");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool PriorityCampaign {
            get {
                return this.priorityCampaignField;
            }
            set {
                this.priorityCampaignField = value;
                this.RaisePropertyChanged("PriorityCampaign");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CampaignData {
            get {
                return this.campaignDataField;
            }
            set {
                this.campaignDataField = value;
                this.RaisePropertyChanged("CampaignData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ObjScreenPop : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int callIdField;
        
        private int campaignIdField;
        
        private string phoneNumberField;
        
        private string campaignDataField;
        
        private string customerIdField;
        
        private int agentIdOriginField;
        
        private int campaignIdOriginField;
        
        private bool readOnlyField;
        
        private string campaignCodeField;
        
        private string tableNameField;
        
        private bool priorityCampaignField;
        
        private string[] phoneNumberListField;
        
        private bool previewCallField;
        
        private bool automaticPreviewCallField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int CallId {
            get {
                return this.callIdField;
            }
            set {
                this.callIdField = value;
                this.RaisePropertyChanged("CallId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int CampaignId {
            get {
                return this.campaignIdField;
            }
            set {
                this.campaignIdField = value;
                this.RaisePropertyChanged("CampaignId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
                this.RaisePropertyChanged("PhoneNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CampaignData {
            get {
                return this.campaignDataField;
            }
            set {
                this.campaignDataField = value;
                this.RaisePropertyChanged("CampaignData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CustomerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
                this.RaisePropertyChanged("CustomerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int AgentIdOrigin {
            get {
                return this.agentIdOriginField;
            }
            set {
                this.agentIdOriginField = value;
                this.RaisePropertyChanged("AgentIdOrigin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int CampaignIdOrigin {
            get {
                return this.campaignIdOriginField;
            }
            set {
                this.campaignIdOriginField = value;
                this.RaisePropertyChanged("CampaignIdOrigin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool ReadOnly {
            get {
                return this.readOnlyField;
            }
            set {
                this.readOnlyField = value;
                this.RaisePropertyChanged("ReadOnly");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string CampaignCode {
            get {
                return this.campaignCodeField;
            }
            set {
                this.campaignCodeField = value;
                this.RaisePropertyChanged("CampaignCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string TableName {
            get {
                return this.tableNameField;
            }
            set {
                this.tableNameField = value;
                this.RaisePropertyChanged("TableName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool PriorityCampaign {
            get {
                return this.priorityCampaignField;
            }
            set {
                this.priorityCampaignField = value;
                this.RaisePropertyChanged("PriorityCampaign");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=11)]
        public string[] PhoneNumberList {
            get {
                return this.phoneNumberListField;
            }
            set {
                this.phoneNumberListField = value;
                this.RaisePropertyChanged("PhoneNumberList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public bool PreviewCall {
            get {
                return this.previewCallField;
            }
            set {
                this.previewCallField = value;
                this.RaisePropertyChanged("PreviewCall");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public bool AutomaticPreviewCall {
            get {
                return this.automaticPreviewCallField;
            }
            set {
                this.automaticPreviewCallField = value;
                this.RaisePropertyChanged("AutomaticPreviewCall");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ObjAgentChangeStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int agentIdField;
        
        private EnumAgentStatusId agentStatusIdField;
        
        private int reasonIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int AgentId {
            get {
                return this.agentIdField;
            }
            set {
                this.agentIdField = value;
                this.RaisePropertyChanged("AgentId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public EnumAgentStatusId AgentStatusId {
            get {
                return this.agentStatusIdField;
            }
            set {
                this.agentStatusIdField = value;
                this.RaisePropertyChanged("AgentStatusId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int ReasonId {
            get {
                return this.reasonIdField;
            }
            set {
                this.reasonIdField = value;
                this.RaisePropertyChanged("ReasonId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum EnumAgentStatusId {
        
        /// <remarks/>
        Nothing,
        
        /// <remarks/>
        Idle,
        
        /// <remarks/>
        Talking,
        
        /// <remarks/>
        Wrap,
        
        /// <remarks/>
        Pause,
        
        /// <remarks/>
        Ending,
        
        /// <remarks/>
        TalkingWithPause,
        
        /// <remarks/>
        WrapWithPause,
        
        /// <remarks/>
        TalkingWithEnding,
        
        /// <remarks/>
        WrapWithEnding,
        
        /// <remarks/>
        Consulting,
        
        /// <remarks/>
        InChat,
        
        /// <remarks/>
        InChatWithPause,
        
        /// <remarks/>
        InChatWithEnding,
        
        /// <remarks/>
        ConsultingWithPause,
        
        /// <remarks/>
        ConsultingWithEnding,
        
        /// <remarks/>
        Transfer,
        
        /// <remarks/>
        Holding,
        
        /// <remarks/>
        HoldingWithPause,
        
        /// <remarks/>
        HoldingWithEnding,
        
        /// <remarks/>
        ManualCall,
        
        /// <remarks/>
        TalkingWithManualCall,
        
        /// <remarks/>
        WrapWithManualCall,
        
        /// <remarks/>
        ConsultingWithManualCall,
        
        /// <remarks/>
        HoldingWithManualCall,
        
        /// <remarks/>
        Redial,
        
        /// <remarks/>
        PrivateCallback,
        
        /// <remarks/>
        TalkingWithPrivateCallback,
        
        /// <remarks/>
        WrapWithPrivateCallback,
        
        /// <remarks/>
        ManualcallWithPrivateCallback,
        
        /// <remarks/>
        ConsultingWithPrivateCallback,
        
        /// <remarks/>
        HoldingWithPrivateCallback,
        
        /// <remarks/>
        ThirdPartyCampaign,
        
        /// <remarks/>
        PersonalCall,
        
        /// <remarks/>
        TalkingWithPersonalCall,
        
        /// <remarks/>
        WrapWithPersonalCall,
        
        /// <remarks/>
        ManualcallWithPersonalCall,
        
        /// <remarks/>
        ConsultingWithPersonalCall,
        
        /// <remarks/>
        HoldingWithPersonalCall,
        
        /// <remarks/>
        PersonalCallWithPause,
        
        /// <remarks/>
        PersonalCallWithEnding,
        
        /// <remarks/>
        Analyzing,
        
        /// <remarks/>
        Attempting,
        
        /// <remarks/>
        Waiting,
        
        /// <remarks/>
        AnalyzingWithPause,
        
        /// <remarks/>
        AnalyzingWithEnding,
        
        /// <remarks/>
        AnalyzingWithPrivateCallback,
        
        /// <remarks/>
        AnalyzingWithPersonalCall,
        
        /// <remarks/>
        AttemptingWithPause,
        
        /// <remarks/>
        AttemptingWithEnding,
        
        /// <remarks/>
        AttemptingWithPersonalCall,
        
        /// <remarks/>
        AttemptingWithPrivateCallback,
        
        /// <remarks/>
        AfterAttempting,
        
        /// <remarks/>
        AfterAttemptWithPersonalCall,
        
        /// <remarks/>
        RedialWithPersonalCall,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ObjLogout : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int agentIdField;
        
        private int campaignIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int AgentId {
            get {
                return this.agentIdField;
            }
            set {
                this.agentIdField = value;
                this.RaisePropertyChanged("AgentId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int CampaignId {
            get {
                return this.campaignIdField;
            }
            set {
                this.campaignIdField = value;
                this.RaisePropertyChanged("CampaignId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ObjLoginCampaign : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int agentIdField;
        
        private int campaignIdField;
        
        private string campaignNameField;
        
        private string campaignCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int AgentId {
            get {
                return this.agentIdField;
            }
            set {
                this.agentIdField = value;
                this.RaisePropertyChanged("AgentId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int CampaignId {
            get {
                return this.campaignIdField;
            }
            set {
                this.campaignIdField = value;
                this.RaisePropertyChanged("CampaignId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CampaignName {
            get {
                return this.campaignNameField;
            }
            set {
                this.campaignNameField = value;
                this.RaisePropertyChanged("CampaignName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CampaignCode {
            get {
                return this.campaignCodeField;
            }
            set {
                this.campaignCodeField = value;
                this.RaisePropertyChanged("CampaignCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ObjNewMsgFromSupervisor : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int messageIdField;
        
        private int broadcastIdField;
        
        private int agentIdField;
        
        private int supervisorIdField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int MessageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
                this.RaisePropertyChanged("MessageId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int BroadcastId {
            get {
                return this.broadcastIdField;
            }
            set {
                this.broadcastIdField = value;
                this.RaisePropertyChanged("BroadcastId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int AgentId {
            get {
                return this.agentIdField;
            }
            set {
                this.agentIdField = value;
                this.RaisePropertyChanged("AgentId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int SupervisorId {
            get {
                return this.supervisorIdField;
            }
            set {
                this.supervisorIdField = value;
                this.RaisePropertyChanged("SupervisorId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ObjSendMsgToSupervisorFail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int agentIdField;
        
        private SendMessageResult reasonField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int AgentId {
            get {
                return this.agentIdField;
            }
            set {
                this.agentIdField = value;
                this.RaisePropertyChanged("AgentId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public SendMessageResult Reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
                this.RaisePropertyChanged("Reason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum SendMessageResult {
        
        /// <remarks/>
        GenericError,
        
        /// <remarks/>
        Ok,
        
        /// <remarks/>
        AgentIdNotFound,
        
        /// <remarks/>
        SupervisorNotFound,
        
        /// <remarks/>
        ServiceNotAvail,
        
        /// <remarks/>
        SysConfNotFound,
        
        /// <remarks/>
        NotSupervisorOfAgent,
        
        /// <remarks/>
        EmptyMessage,
        
        /// <remarks/>
        MessageTooLong,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ObjLoginCCM : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int agentIdField;
        
        private string agentNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int AgentId {
            get {
                return this.agentIdField;
            }
            set {
                this.agentIdField = value;
                this.RaisePropertyChanged("AgentId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AgentName {
            get {
                return this.agentNameField;
            }
            set {
                this.agentNameField = value;
                this.RaisePropertyChanged("AgentName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSAgentEventSoapChannel : Callplus.CRM.Tabulador.App.WSAgentEvent.WSAgentEventSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSAgentEventSoapClient : System.ServiceModel.ClientBase<Callplus.CRM.Tabulador.App.WSAgentEvent.WSAgentEventSoap>, Callplus.CRM.Tabulador.App.WSAgentEvent.WSAgentEventSoap {
        
        public WSAgentEventSoapClient() {
        }
        
        public WSAgentEventSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSAgentEventSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSAgentEventSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSAgentEventSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Callplus.CRM.Tabulador.App.WSAgentEvent.ObjEvent GetNextEvent(int AgentId) {
            return base.Channel.GetNextEvent(AgentId);
        }
        
        public System.Threading.Tasks.Task<Callplus.CRM.Tabulador.App.WSAgentEvent.ObjEvent> GetNextEventAsync(int AgentId) {
            return base.Channel.GetNextEventAsync(AgentId);
        }
        
        public Callplus.CRM.Tabulador.App.WSAgentEvent.ObjEvent[] GetAllNextEvents() {
            return base.Channel.GetAllNextEvents();
        }
        
        public System.Threading.Tasks.Task<Callplus.CRM.Tabulador.App.WSAgentEvent.ObjEvent[]> GetAllNextEventsAsync() {
            return base.Channel.GetAllNextEventsAsync();
        }
    }
}
